1. What is a Python library? Why do we use Python libraries?

A Python library is a collection of modules or packages that provide pre-written and reusable code to perform specific tasks or functions. These libraries contain functions, classes, and methods that you can use in your Python programs to save time and effort, as you don't have to write the code from scratch.

Python libraries are created to address various needs, such as data manipulation, numerical computations, web development, machine learning, and more. Some popular Python libraries include:

- NumPy: Used for numerical computing, providing support for large, multi-dimensional arrays and matrices, along with mathematical functions.

- Pandas: A powerful library for data manipulation and analysis, offering data structures like DataFrames for efficient handling and analysis of structured data.

- Matplotlib and Seaborn: Libraries for creating static, animated, and interactive visualizations in Python.

- Requests: Simplifies HTTP requests, making it easier to interact with web services and APIs.

- Django and Flask: Web frameworks for building web applications in Python, each with its own approach and set of features.

- TensorFlow and PyTorch: Popular libraries for machine learning and deep learning, providing tools for building and training neural networks.

- Beautiful Soup and Scrapy: Used for web scraping, enabling the extraction of data from HTML and XML documents.

- Scikit-learn: A machine learning library that provides simple and efficient tools for data mining and data analysis.

- NLTK (Natural Language Toolkit): A library for working with human language data, useful for tasks such as text processing and analysis.

- OpenCV: A computer vision library that provides tools for image and video analysis.

Python libraries are used for several reasons, providing a wide range of benefits to developers. Here are some key reasons why Python libraries are extensively used:
- Efficiency: Libraries contain pre-written code for common tasks, allowing developers to leverage existing solutions rather than writing code from scratch. This significantly speeds up the development process.

- Code Reusability: Libraries provide reusable components that can be easily integrated into different projects. This promotes the reuse of well-tested and proven code, reducing redundancy and improving maintainability.

- Community Collaboration: Python has a large and active community of developers who contribute to the creation and maintenance of libraries. This collaborative effort leads to the development of high-quality, feature-rich libraries that address various needs.

- Specialized Functionality: Python libraries are often designed to address specific tasks or domains, such as data analysis, machine learning, web development, and more. Using specialized libraries allows developers to benefit from the expertise of others in those particular areas.

- Rapid Prototyping: Libraries provide ready-to-use tools that enable rapid prototyping and experimentation. This is particularly valuable in fields like data science and machine learning, where quick iterations and testing different algorithms are common.

- Standardization: Certain libraries become de facto standards in their respective domains. For example, NumPy and Pandas are widely adopted for numerical computing and data manipulation in the Python ecosystem. This standardization promotes interoperability and a shared knowledge base among developers.

- Performance Optimization: Many libraries are implemented in lower-level languages like C or C++ for performance reasons. By using these libraries, developers can benefit from optimized code without sacrificing the ease of use and expressiveness of Python.

- Open Source Philosophy: Many Python libraries are open source, encouraging collaboration and allowing developers to inspect, modify, and contribute to the codebase. This fosters transparency and innovation within the Python ecosystem.

- Cross-Platform Compatibility: Python libraries are designed to be cross-platform, allowing developers to write code that can run on different operating systems without modification. This enhances portability and broadens the reach of applications.

- Documentation and Support: Well-maintained libraries often come with comprehensive documentation and community support. This makes it easier for developers to understand how to use the library effectively and seek help when needed.

2. What is the difference between Numpy array and List?

Difference between Numpy array and List are:

- Data Type Storage :
    - List - Lists can store any datatype (l = [25, 33.0078, 'hello'])
    - Numpy array - It can store only one datatype (a = [45,78,63,900,45])
 
- Importing Modules
    - List - Lists are inbuilt data structures in python and we do not need to install them separetely
    - Numpy array - To use numpy arrays we need to install numpy package and import it to work on it
 
- Numerical Operations
    - List - we cannot perform much numerical operations on lists. It cannot be used as a matrix
    - Numpy array - In numpy arrays there are many functions available to perform these operations. For example, we use numpy in image processing as it can also be used as a matrix.
 
- Modification Capabilities
    - List - More functions are available to modify lists
    - Numpy array - we can resize or reshape numpy arrays. elements can alsoo be updated 
 
- Memory Usage
    - List - It consumes more memory
    - Numpy array - it consumes less memory
        - Fixed size
        - homogenous datatype
        - contaguous memory allocation
 
- 
    - List - It is comparatively slow. We can calculate their implementation time by using following :
        - %timeit - for single line execution
        - %%timeit - for whole program
    - Numpy array -  NumPy's speed is a result of its efficient implementation in low-level languages, support for vectorized operations and broadcasting, optimized algorithms, memory efficiency, and the ongoing contributions from the open-source community.
 
- Numpy arrays are convinient to use for large datasets

3. Find the shape, size and dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]


In [1]:
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(f'Shape of array is {arr.shape}')
print(f'Size of array is {arr.size}')

Shape of array is (3, 4)
Size of array is 12




4. Write python code to access the first row of the following array?

[[1, 2, 3, 4],

[5, 6, 7, 8],

[9, 10, 11, 12]]




In [2]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

first_row = arr[0,:]
print(f'First row : {first_row}')

First row : [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [3]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

# starting index is 0, 3rd row is denoted by 2 and 4th col is denoted by 3
arr[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]




In [4]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]

print(f'Odd indexed elements are : {odd_indexed_elements}')

Odd indexed elements are : [[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?




In [5]:
random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)

Random 3x3 matrix:
[[0.69800102 0.14886526 0.53622273]
 [0.64813965 0.04968098 0.1962981 ]
 [0.55185318 0.06789823 0.53202705]]


8. Describe the difference between np.random.rand and np.random.randn?

1. np.random.rand:
    - This function generates random values from a uniform distribution over the interval [0, 1).
    - All values have an equal probability of being selected.

2. np.random.randn:
    -  This function generates random values from a standard normal distribution (mean = 0, standard deviation = 1).
    - The values are more likely to be closer to 0, and the distribution follows a bell-shaped curve (normal distribution or Gaussian distribution).

In [6]:
random_mat = np.random.rand(3,3)
print(f'Random Matrix {random_mat}')

random_n_mat = np.random.randn(3,3)
print(f'\nRandom n Matrix {random_n_mat}')

Random Matrix [[0.81615019 0.42897588 0.76061205]
 [0.53755542 0.91013858 0.13782239]
 [0.79292316 0.38382768 0.53837829]]

Random n Matrix [[ 1.40437006  1.20480051  0.04071681]
 [-1.59992087 -1.71143345  0.56487583]
 [-0.34568434 -0.88448237  0.95252637]]


9. Write code to increase the dimension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]




In [7]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

new_arr = np.expand_dims(arr, axis = 0)
new_arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]




In [8]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr.transpose())

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:

Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python
Index wise multiplicatio
Matrix multiplicatio
Add both the matric
Subtract matrix B from
Divide Matrix B by A




In [9]:
mat_a = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
mat_b = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [10]:
#  Index wise multiplication
mul = mat_a * mat_b
mul

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [11]:
# add
add = mat_a + mat_b
add

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [12]:
# subtract
sub = mat_a - mat_b
sub

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
# divide
div = mat_b / mat_a
div

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?



In [40]:
arr = np.array([1, 2, 3, 4])
print(arr.byteswap())

[16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?



We use np.linalg.inv() function to calculate the inverse of a matrix. The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.

In [14]:
arr = np.array([[1,2,3],[5,7,8],[1,1,2]])
inverse =  np.linalg.inv(arr)
inverse

array([[-1.5 ,  0.25,  1.25],
       [ 0.5 ,  0.25, -1.75],
       [ 0.5 , -0.25,  0.75]])

In [15]:
# returning identity matrix
np.dot(arr,inverse)

array([[ 1.0000000e+00,  0.0000000e+00, -4.4408921e-16],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

14. What does the np.reshape function do, and how is it used?



The numpy.reshape() function rearranges the data in an ndarray into a new shape. The new shape must be compatible with the old one, though an index of -1 can be used to infer one dimension.
Means if the shape of a matrix was [3,6] before, so when we multiply '3x6' gives '18'. then the new shape should be when multiplied give '18', so that all the elements can be rightly fit inside it.

In [25]:
arr = np.random.randint(1,10,(5,6))

In [26]:
arr

array([[8, 6, 6, 5, 7, 7],
       [9, 5, 5, 3, 2, 8],
       [2, 7, 7, 2, 6, 6],
       [6, 9, 1, 3, 2, 9],
       [2, 4, 8, 4, 8, 1]])

In [27]:
arr.shape

(5, 6)

In [29]:
arr.reshape(15,2)

array([[8, 6],
       [6, 5],
       [7, 7],
       [9, 5],
       [5, 3],
       [2, 8],
       [2, 7],
       [7, 2],
       [6, 6],
       [6, 9],
       [1, 3],
       [2, 9],
       [2, 4],
       [8, 4],
       [8, 1]])

In [30]:
arr.reshape(3,10)

array([[8, 6, 6, 5, 7, 7, 9, 5, 5, 3],
       [2, 8, 2, 7, 7, 2, 6, 6, 6, 9],
       [1, 3, 2, 9, 2, 4, 8, 4, 8, 1]])

15. What is broadcasting in Numpy?


The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.<br><br>
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when
- they are equal, or
- one of them is 1.

In [37]:
a = np.array([[1,2,3,4],[3,4,2,1],[2,2,0,3]])
b = np.array([3])
a+b

array([[4, 5, 6, 7],
       [6, 7, 5, 4],
       [5, 5, 3, 6]])